header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: NWChemEx-Project

  paths-ignore:
    - .github/
    - docs/Makefile
    - LICENSE
    - docs/requirements.txt
    - docs/source/bibliography/*.bib
    - version.txt
    - cmake/friends.py.in

  comment: never
